### ISSUE TITLE
How to change the cursor color?

### ISSUE THREAD

**Issue by ndfz** [blazkowolf/gruber-darker.nvim#7]
Hello, I would like to change the cursor color. How can I do that? I installed the plugin using Lazy:
```lua
return {
  "blazkowolf/gruber-darker.nvim",
  name = "gruber-darker",
  opts = {},
}
```
I'm sorry if the question was very silly, I'm not familiar with Lua very well. Thank you for your interesting project.

**Comment by ndfz** [comment]
I solved my problem by redefining the cursor as follows:
```lua
return { 
  Cursor = { fg = "#ffffff" },
}
```
The answer to the question turned out to be really silly. I'm sorry.

**Comment by blazkowolf** [comment]
Thank you for your interest! This is not a silly question by any means. Currently, I haven't built in a way to customize highlights, but it's something I plan on doing eventually.
