### ISSUE TITLE
issue with bg color for fold text too much white

### ISSUE THREAD

**Issue by AhmadFudl** [blazkowolf/gruber-darker.nvim#8]
![Screenshot 2023-08-22 at 7 54 19 PM](https://github.com/blazkowolf/gruber-darker.nvim/assets/57303112/dabdaaae-8ee1-4180-966c-7f5ee583e48a)

**Comment by blazkowolf** [comment]
I agree - this was an oversight on my part. I'll make an update to the highlights this evening when I have some free time!

**Comment by blazkowolf** [comment]
I pushed a change that updated the bg color for folds to `bg+2` which is a much more visually consistent color for those highlight groups.
![image](https://github.com/blazkowolf/gruber-darker.nvim/assets/9439488/902ebf07-1b24-4e60-beeb-d46e0de89d4a)
